/** Player craft catalog. */
import type { CraftKind, CraftSpec } from "../sim/crafts";

/** Catalog of player-selectable craft. */
const CRAFTS_DEFS: Record<CraftKind, Omit<CraftSpec, "kind">> = {
  apache: {
    name: "Apache",
    fullName: "AH-64E Apache",
    role: "Heavy Gunship",
    description: "An agile yet heavily armored tank-killer, the Apache dominates the battlefield by raining down precision missile strikes and devastating cannon fire from above.",
    flightModel: "heli",
    sizeM: 14.7,
    ammoScale: 1,
    health: 100,
    radius: 20,
    height: 14,
    body: "craft_apache",
    hulk: "craft_apache_hulk",
    rotor: "craft_apache_rotor",
    rotorHulk: "craft_apache_rotor_hulk",
    rotOff: Math.PI / 2,
    forwardThrust: 520, strafeThrust: 340, maxSpeed: 340, minSpeed: 0, yawRate: 2.55, yawAccel: 11, drag: 1.65,
    verticalThrust: 340, cruiseThrust: 36, cruiseAgl: 46, maxAgl: 118,
    sockets: [
      { id: "chin_turret", class: "turret", controller: "pilot", weapon: "chain_gun", traverse: 240 },
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "rocket" },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "hellfire_missile" },
      { id: "wing_hardpoint_3", class: "hardpoint", controller: "pilot", weapon: "tv_missile" },
    ],
  },
  little_bird: {
    name: "Little Bird",
    fullName: "AH-6 Little Bird",
    role: "Knife Fighter",
    description: "An ultra-nimble knife fighter, the Little Bird weaves through tight landscapes to deploy precise strikes, shredding enemies with rapid minigun fire.",
    flightModel: "heli",
    sizeM: 9.94,
    ammoScale: 0.7,
    health: 70,
    radius: 14,
    height: 8,
    body: "craft_littlebird",
    hulk: "craft_littlebird_hulk",
    rotor: "craft_littlebird_rotor",
    rotorHulk: "craft_littlebird_rotor_hulk",
    rotorScale: 0.71,
    rotOff: Math.PI / 2,
    forwardThrust: 660, strafeThrust: 560, maxSpeed: 390, minSpeed: 0, yawRate: 4.1, yawAccel: 22, drag: 1.25,
    verticalThrust: 520, cruiseThrust: 52, cruiseAgl: 46, maxAgl: 118,
    sockets: [
      {
        id: "wing_gun_l",
        class: "fixed",
        controller: "pilot",
        weapon: "minigun",
        points: [{ id: "wing0" }, { id: "wing1" }],
        muzzleFire: "simultaneous",
      },
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "rocket" },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "stinger_missile" },
      // Twin gun pods, not ordnance — fixed + simultaneous like wing_gun_l, so both pods fire
      // together instead of alternating single shots the way a missile rack would.
      {
        id: "wing_hardpoint_3",
        class: "fixed",
        controller: "pilot",
        weapon: "heavy_cal_pod",
        points: [{ id: "pod_l" }, { id: "pod_r" }],
        muzzleFire: "simultaneous",
      },
    ],
  },
  cobra: {
    name: "Cobra",
    fullName: "AH-1 Cobra",
    role: "Agile Striker",
    description: "A razor-thin and lightning-fast gunship, the Cobra cuts through hostile airspace to orchestrate relentless close-air support and tear apart ground convoys.",
    flightModel: "heli",
    // IRL AH-1 shorter than Apache; keep under Apache's sizeM baseline.
    sizeM: 13.4,
    ammoScale: 0.9,
    health: 82,
    radius: 16,
    height: 13,
    // Slimmer silhouette → slightly harder for enemies to notice than Apache.
    enemyAwareMul: 0.92,
    body: "craft_cobra",
    hulk: "craft_cobra_hulk",
    sensorPalette: "night_vision",
    rotor: "craft_cobra_rotor",
    rotorHulk: "craft_cobra_rotor_hulk",
    rotorScale: 1.24,
    rotOff: Math.PI / 2,
    gunOverlayScale: 0.42,
    // Hot-rod classic: snappier than Apache/Viper, thinner skin.
    forwardThrust: 640, strafeThrust: 450, maxSpeed: 395, minSpeed: 0, yawRate: 3.45, yawAccel: 18.5, drag: 1.35,
    verticalThrust: 440, cruiseThrust: 46, cruiseAgl: 46, maxAgl: 118,
    sockets: [
      { id: "chin_turret", class: "turret", controller: "pilot", weapon: "gatling", traverse: 280 },
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "rocket", ammoMul: 1.45 },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "sidewinder_missile" },
      { id: "wing_hardpoint_3", class: "hardpoint", controller: "pilot", weapon: "tow_missile" },
    ],
  },
  viper: {
    name: "Viper",
    fullName: "AH-1Z Viper",
    role: "Strike Interceptor",
    description: "A blazing-fast and hyper-agile hunter, the Viper tears through coastal and contested airspace to dominate dogfights and shred targets with a high-speed Gatling gun.",
    flightModel: "heli",
    // Same silhouette class as Cobra; under Apache sizeM.
    sizeM: 13.4,
    ammoScale: 0.95,
    health: 90,
    radius: 16,
    height: 13,
    enemyAwareMul: 0.92,
    body: "craft_viper",
    hulk: "craft_viper_hulk",
    rotor: "craft_viper_rotor",
    rotorHulk: "craft_viper_rotor_hulk",
    rotorScale: 1.24,
    gunOverlayScale: 0.42,
    rotOff: Math.PI / 2,
    // Between Cobra and Apache: slightly less snap than Cobra, still a striker.
    forwardThrust: 620, strafeThrust: 430, maxSpeed: 385, minSpeed: 0, yawRate: 3.3, yawAccel: 17, drag: 1.38,
    verticalThrust: 425, cruiseThrust: 44, cruiseAgl: 48, maxAgl: 122,
    sockets: [
      { id: "chin_turret", class: "turret", controller: "pilot", weapon: "gatling", traverse: 280 },
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "rocket" },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "hellfire_missile" },
      { id: "wing_hardpoint_3", class: "hardpoint", controller: "pilot", weapon: "tow_missile", ammoMul: 8 / 7 },
    ],
  },
  blackhawk: {
    name: "Black Hawk",
    fullName: "UH-60M Black Hawk",
    role: "Assault Transport",
    description: "A heavily armored gunship platform, the Black Hawk locks down the battlefield with relentless side-door minigun fire and wings stacked with heavy rockets.",
    flightModel: "heli",
    sizeM: 19.76,
    ammoScale: 1.3,
    health: 135,
    radius: 27,
    height: 15,
    body: "craft_blackhawk",
    hulk: "craft_blackhawk_hulk",
    sensorPalette: "black_hot",
    rotor: "craft_blackhawk_rotor",
    rotorHulk: "craft_blackhawk_rotor_hulk",
    rotorScale: 1.39,
    rotOff: Math.PI / 2,
    forwardThrust: 450, strafeThrust: 260, maxSpeed: 280, minSpeed: 0, yawRate: 1.95, yawAccel: 8, drag: 1.85,
    verticalThrust: 300, cruiseThrust: 32, cruiseAgl: 46, maxAgl: 118,
    liftClass: "medium",
    sockets: [
      { id: "wing_guns", class: "fixed", controller: "pilot", weapon: "gatling", muzzleFire: "simultaneous" },
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "rocket" },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "hellfire_missile" },
      // Door guns: explicit points ↔ heading.
      {
        id: "cabin_doors",
        class: "turret",
        controller: "automatic",
        weapon: "machine_gun",
        points: [
          { id: "door_l", heading: -75 },
          { id: "door_r", heading: 75 },
        ],
        traverse: 270,
        crew: "door",
      },
    ],
  },
  chinook: {
    name: "Chinook",
    fullName: "CH-47F Chinook",
    role: "Heavy Ordnance",
    description: "A massive and heavy-hitting behemoth, the Chinook completely blankets the warzone by carpet-bombing enemy lines and unleashing overwhelming crossfire from a battery of door gunners.",
    flightModel: "heli",
    // Both guns are crew-automatic (fwd_l/fwd_r ±50°, ramp 180°) — the nose doesn't need to chase
    // the mouse to bring them to bear. Loiter controls (yaw on keys, mouse free-aims the bomb
    // reticle) suit "circle a target and let the door gunners rake it" better than a dogfighter's
    // nose-follow.
    controlScheme: "orbit",
    sizeM: 30.1,
    ammoScale: 1.6,
    health: 420,
    radius: 41,
    height: 25,
    body: "craft_chinook",
    hulk: "craft_chinook_hulk",
    sensorPalette: "black_hot",
    rotor: "craft_chinook_rotor",
    rotorHulk: "craft_chinook_rotor_hulk",
    rotorScale: 1.55,
    rotOff: Math.PI / 2,
    forwardThrust: 520, strafeThrust: 280, maxSpeed: 310, minSpeed: 0, yawRate: 0.72, yawAccel: 3.4, drag: 1.65,
    verticalThrust: 340, cruiseThrust: 34, cruiseAgl: 48, maxAgl: 125,
    liftClass: "heavy",
    sockets: [
      // Forward cabin guns: explicit mount ↔ heading (same multi-mount model as Black Hawk doors).
      {
        id: "cabin_forward",
        class: "turret",
        controller: "automatic",
        weapon: "machine_gun",
        points: [
          { id: "fwd_l", heading: -50 },
          { id: "fwd_r", heading: 50 },
        ],
        traverse: 240,
      },
      // Heavy lift: low momentum inherit so hover / reverse drops can go where aimed.
      {
        id: "bomb_bay_1",
        class: "hardpoint",
        controller: "pilot",
        weapon: "heavy_bomb",
        // Side stub bays only — not the tail cargo_ramp.
        points: [{ id: "hardpoint0" }, { id: "hardpoint1" }],
        bombDrop: { momentum: 0.28, maxBoost: 240, loft: 130, loftMax: 230 },
      },
      {
        id: "bomb_bay_2",
        class: "hardpoint",
        controller: "pilot",
        weapon: "cluster_bomb",
        // Side stub bays only — not the tail cargo_ramp.
        points: [{ id: "hardpoint0" }, { id: "hardpoint1" }],
        bombDrop: { momentum: 0.28, maxBoost: 240, loft: 130, loftMax: 230 },
      },
      // Ramp gun faces aft.
      {
        id: "cabin_ramp",
        class: "turret",
        controller: "automatic",
        weapon: "heavy_machine_gun",
        points: [{ id: "ramp", heading: 180 }],
        traverse: 270,
        crew: "ramp",
      },
      { id: "cargo_bay", class: "hardpoint", controller: "pilot", weapon: "humvee_drop", points: [{ id: "cargo_ramp" }], heading: 180, ammo: 2 },
    ],
  },
  osprey: {
    name: "Osprey",
    fullName: "MV-22B Osprey",
    role: "Hybrid Assault",
    description: "A swift, tilt-rotor assault platform, the Osprey shifts seamlessly from high-speed flight to hovering over hot zones with a heavy array of multi-directional turrets and rockets.",
    flightModel: "vtol",
    sizeM: 25.8,
    ammoScale: 1.4,
    health: 140,
    radius: 35,
    height: 20,
    body: "craft_osprey",
    hulk: "craft_osprey_hulk",
    rotor: "craft_osprey_rotor",
    rotorHulk: "craft_osprey_rotor_hulk",
    rotorScale: 0.98,
    rotOff: Math.PI / 2,
    forwardThrust: 700, strafeThrust: 230, maxSpeed: 430, minSpeed: 0, yawRate: 1.7, yawAccel: 7, drag: 1.4,
    verticalThrust: 380, cruiseThrust: 40, cruiseAgl: 70, maxAgl: 170,
    liftClass: "heavy",
    sockets: [
      {
        id: "belly_turret",
        class: "turret",
        controller: "automatic",
        weapon: "minigun",
        points: [{ id: "belly" }],
        traverse: 360,
        crew: "belly",
      },
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "guided_rockets", ammoMul: 1.25 },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "hellfire_missile" },
      {
        id: "cabin_ramp",
        class: "turret",
        controller: "automatic",
        weapon: "heavy_machine_gun",
        points: [{ id: "ramp", heading: 180 }],
        traverse: 270,
        crew: "ramp",
      },
      { id: "cargo_bay", class: "hardpoint", controller: "pilot", weapon: "wolf_drop", points: [{ id: "cargo_ramp" }], heading: 180, ammo: 1 },
    ],
  },
  stealthhawk: {
    name: "Stealth Hawk",
    fullName: "XH-60 Stealth Hawk",
    role: "Stealth Attack",
    description: "A ghostly and evasive scout, the Stealth Hawk slips past enemy radar grids to ambush high-value targets before vanishing back into the shadows.",
    flightModel: "heli",
    sizeM: 14.7,
    ammoScale: 1,
    health: 110,
    radius: 20,
    height: 14,
    body: "craft_stealthhawk",
    hulk: "craft_stealthhawk_hulk",
    rotor: "craft_stealthhawk_rotor",
    rotorHulk: "craft_stealthhawk_rotor_hulk",
    rotorScale: 1.24,
    rotOff: Math.PI / 2,
    forwardThrust: 475, strafeThrust: 310, maxSpeed: 305, minSpeed: 0, yawRate: 2.45, yawAccel: 10.5, drag: 1.65,
    verticalThrust: 340, cruiseThrust: 36, cruiseAgl: 46, maxAgl: 118,
    sockets: [
      { id: "chin_turret", class: "turret", controller: "pilot", weapon: "concealed_cannon", traverse: 220 },
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "microwave_missile", ammoMul: 0.75 },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "stinger_missile" },
      { id: "wing_hardpoint_3", class: "hardpoint", controller: "pilot", weapon: "smoke_bomb" },
    ],
    enemyAimMul: 0.55,
    enemySeekerMul: 0.22,
    enemyAwareMul: 0.32,
    countermeasure: "emp",
  },
  cyberhawk: {
    name: "Cyber Hawk",
    fullName: "XH-88 Cyber Hawk",
    role: "High-tech Offensive",
    description: "A high-tech predator, the Cyber Hawk breaks through enemy defenses with devastating electronic warfare.",
    flightModel: "heli",
    sizeM: 14.7,
    ammoScale: 1.05,
    // Glass cannon: Time Warp is its survival tool, not the hull.
    health: 80,
    radius: 20,
    height: 14,
    body: "craft_cyberhawk",
    hulk: "craft_cyberhawk_hulk",
    rotor: "craft_cyberhawk_rotor",
    rotorHulk: "craft_cyberhawk_rotor_hulk",
    rotorScale: 1,
    rotOff: Math.PI / 2,
    forwardThrust: 740, strafeThrust: 500, maxSpeed: 500, minSpeed: 0, yawRate: 3.35, yawAccel: 16, drag: 1.2,
    verticalThrust: 480, cruiseThrust: 48, cruiseAgl: 46, maxAgl: 118,
    exhaustProfile: {
      rate: 32, speed: 105, tint: 0x70d8ff, smoke: 0x485761, sx: 1.05, sy: 0.26, life: 1180, flame: 0.5, gap: 9, flameHue: 172,
    },
    sockets: [
      // Single chin rail — snappier than the catalog / hover dual.
      { id: "chin_turret", class: "turret", controller: "pilot", weapon: "railgun", traverse: 150, fireRateMul: 1.55 },
      { id: "wing_hardpoint", class: "hardpoint", controller: "pilot", weapon: "swarm_missile" },
      { id: "tesla_coil", class: "turret", controller: "pilot", weapon: "tesla_beam", traverse: 150, range: 260 },
      { id: "bomb_bay", class: "hardpoint", controller: "pilot", weapon: "attack_drone" },
    ],
    countermeasure: "timewarp",
    sensorPalette: "full_spectrum",
  },
  quad_drone: {
    name: "Murder Hornet",
    fullName: "MQ-27 Murder Hornet",
    role: "Kill Drone",
    description: "A fast, flying nightmare, the Murder Hornet zips through the skies to eliminate infantry and crack armor with high-velocity kinetic slugs.",
    flightModel: "heli",
    sizeM: 1.9,
    ammoScale: 0.65,
    health: 45,
    radius: 4.5,
    height: 3.2,
    body: "craft_quad_drone",
    hulk: "craft_quad_drone_hulk",
    rotor: "craft_quad_drone_rotor",
    rotorHulk: "craft_quad_drone_rotor_hulk",
    rotorScale: 0.26,
    rotOff: Math.PI / 2,
    forwardThrust: 760, strafeThrust: 700, maxSpeed: 440, minSpeed: 0, yawRate: 8.7, yawAccel: 47, drag: 1.05,
    verticalThrust: 650, cruiseThrust: 60, cruiseAgl: 38, maxAgl: 105,
    sockets: [
      { id: "belly_gun", class: "fixed", controller: "pilot", weapon: "machine_gun",
        points: [{ id: "pod0" }, { id: "pod1" }], muzzleFire: "simultaneous" },
      { id: "belly_coil", class: "fixed", controller: "pilot", weapon: "tesla_beam",
        points: [{ id: "coil" }], range: 138 },
      { id: "wing_hardpoint", class: "hardpoint", controller: "pilot", weapon: "mini_hellfire_missile" },
      {
        id: "bomb_bay",
        class: "hardpoint",
        controller: "pilot",
        weapon: "mini_bomb",
        bombDrop: { momentum: 0.45, maxBoost: 160, loft: 110, loftMax: 190 },
      },
    ],
    countermeasure: "emp",
  },
  // Kamikaze pod. Same quad-drone art as Murder Hornet, own slower flight. Not hangar-selectable.
  spectre: {
    name: "Spectre",
    fullName: "SPECTRE DRONE",
    role: "Kamikaze Drone",
    description: "A bomb with rotors, and your eyes from the cockpit to hit remote targets.",
    playable: false,
    flightModel: "heli",
    sizeM: 1.9,
    ammoScale: 0.65,
    health: 28,
    radius: 7,
    height: 4,
    body: "craft_quad_drone",
    hulk: "craft_quad_drone_hulk",
    rotor: "craft_quad_drone_rotor",
    rotorHulk: "craft_quad_drone_rotor_hulk",
    rotorScale: 0.26,
    rotOff: Math.PI / 2,
    // Same thrust / cap / yaw as the old remote. Drag matches its per-frame bleed
    // (v *= 0.12^dt) so W cruises near 260 instead of sitting on the 360 cap.
    forwardThrust: 560, strafeThrust: 500, maxSpeed: 360, minSpeed: 0, yawRate: 5.4, yawAccel: 29, drag: 2.12,
    verticalThrust: 300, cruiseThrust: 40, cruiseAgl: 26, maxAgl: 90,
    sockets: [],
  },
  lightning_ii: {
    name: "Lightning II",
    fullName: "F-35B Lightning II",
    role: "Fast Attack",
    description: "A supersonic weapon platform, the Lightning II combines lightning-fast jet speeds with lethal VTOL maneuvering to dictate the terms of any engagement.",
    flightModel: "vtol",
    controlScheme: "plane",
    cannonInherit: true,
    sizeM: 15.7,
    ammoScale: 1.5,
    health: 165,
    radius: 31,
    height: 13,
    body: "craft_lightning_ii",
    hulk: "craft_lightning_ii_hulk",
    rotOff: Math.PI / 2,
    forwardThrust: 1050, reverseThrust: 130, strafeThrust: 260, maxSpeed: 680, maxReverseSpeed: 65, minSpeed: 0, yawRate: 2.35, yawAccel: 10, drag: 1.15,
    verticalThrust: 380, cruiseThrust: 40, cruiseAgl: 210, maxAgl: 420,
    exhaustProfile: {
      rate: 56, speed: 160, tint: 0xbfeaff, smoke: 0x3b4145, sx: 1.22, sy: 0.3, life: 1320, flame: 0.72, gap: 6,
      flameHue: 185, ribbonDense: true,
    },
    sockets: [
      { id: "nose_gun", class: "fixed", controller: "pilot", weapon: "medium_gatling_cannon" },
      { id: "internal_bay_1", class: "hardpoint", controller: "pilot", weapon: "light_gps_missile" },
      { id: "wing_hardpoint", class: "hardpoint", controller: "pilot", weapon: "sidewinder_missile" },
      // Fast attack: bombs carry craft speed; little corrective throw.
      {
        id: "internal_bay_2",
        class: "hardpoint",
        controller: "pilot",
        weapon: "gps_bomb",
        // JDAM: less carry, more aim throw — fins do the rest in flight.
        bombDrop: { momentum: 0.48, maxBoost: 185, loft: 105, loftMax: 190 },
      },
    ],
  },
  warthog: {
    name: "Warthog",
    fullName: "A-10C Warthog",
    role: "Tank Buster",
    description: "A terrifyingly fast airborne tank, the Warthog rips through the airspace completely armed to the teeth and anchored by its legendary, armor-shredding rotary cannon.",
    flightModel: "plane",
    controlScheme: "plane",
    cannonInherit: true,
    sizeM: 17.42,
    ammoScale: 1.3,
    health: 150,
    radius: 40,
    height: 13,
    body: "craft_warthog",
    hulk: "craft_warthog_hulk",
    rotOff: Math.PI / 2,
    forwardThrust: 1200, strafeThrust: 0, maxSpeed: 760, minSpeed: 400, yawRate: 1.85, yawAccel: 8.2, drag: 0.75,
    verticalThrust: 180, cruiseThrust: 24, cruiseAgl: 280, maxAgl: 560,
    exhaustProfile: {
      rate: 52, speed: 145, tint: 0xff8a2c, smoke: 0x3d3935, sx: 1.35, sy: 0.34, life: 1420, flame: 0.7, gap: 7,
      flameHue: 0, ribbonDense: true,
    },
    sockets: [
      { id: "nose_gun", class: "fixed", controller: "pilot", weapon: "heavy_cannon" },
      {
        id: "bomb_bay_1",
        class: "hardpoint",
        controller: "pilot",
        weapon: "cluster_bomb",
        // Dumb iron: same craft carry as before, weaker aim correction (vs JDAM bay).
        bombDrop: { momentum: 0.45, maxBoost: 85, loft: 110, loftMax: 195 },
      },
      { id: "wing_hardpoint", class: "hardpoint", controller: "pilot", weapon: "heavy_guided_missile" },
      {
        id: "bomb_bay_2",
        class: "hardpoint",
        controller: "pilot",
        weapon: "gps_bomb",
        bombDrop: { momentum: 0.52, maxBoost: 170, loft: 100, loftMax: 180 },
      },
    ],
  },
  gunship: {
    name: "Gunship",
    fullName: "AC-130 Gunship",
    role: "Loiter Gunship",
    description: "A monolithic angel of death, the AC130 orbits the warzone to rain down a terrifying, unrelenting deluge of heavy artillery and explosive fire from the heavens.",
    flightModel: "plane",
    controlScheme: "orbit",
    sizeM: 39.7,
    ammoScale: 2,
    health: 320,
    radius: 100,
    height: 35,
    body: "craft_gunship",
    hulk: "craft_gunship_hulk",
    rotor: "craft_osprey_rotor",
    rotorHulk: "craft_osprey_rotor_hulk",
    rotorScale: 0.24,
    rotOff: Math.PI / 2,
    forwardThrust: 580, strafeThrust: 0, maxSpeed: 340, minSpeed: 200, yawRate: 0.45, yawAccel: 1.3, drag: 1.25,
    verticalThrust: 90, cruiseThrust: 14, cruiseAgl: 320, maxAgl: 520,
    sockets: [
      {
        id: "cabin_gun_1",
        class: "turret",
        controller: "automatic",
        weapon: "heavy_artillery",
        points: [{ id: "howitzer" }],
        gunScale: 1.25,
        heading: -90,
        traverse: 160,
        crew: "door",
      },
      {
        id: "cabin_gun_2",
        class: "turret",
        controller: "automatic",
        weapon: "medium_cannon",
        points: [{ id: "bofors" }],
        gunScale: 0.85,
        heading: -90,
        traverse: 160,
        crew: "door",
      },
      {
        id: "cabin_gun_3",
        class: "turret",
        controller: "automatic",
        weapon: "light_cannon",
        points: [{ id: "spooky" }],
        gunScale: 0.65,
        heading: -90,
        traverse: 160,
        crew: "door",
      },
      {
        id: "wing_hardpoint",
        class: "hardpoint",
        controller: "pilot",
        weapon: "gps_missile",
      },
    ],
    sensorPalette: "white_hot",
  },
  reaper: {
    name: "Reaper",
    fullName: "MQ-9 Reaper",
    role: "Loiter Hunter",
    description: "Death from above, the Reaper stalks the battlefield from extreme range to deliver sudden, surgical missile strikes on unsuspecting targets.",
    flightModel: "plane",
    controlScheme: "orbit",
    sizeM: 20,
    ammoScale: 1.1,
    health: 90,
    radius: 36,
    height: 8,
    body: "craft_reaper",
    hulk: "craft_reaper_hulk",
    rotOff: Math.PI / 2,
    // Orbit loiter like Gunship: A/D turn, W/S trim; mouse aims stores.
    // Cruise above tank/building lob ceilings; helis can still climb to meet.
    forwardThrust: 480, strafeThrust: 0, maxSpeed: 360, minSpeed: 160, yawRate: 1.05, yawAccel: 3.2, drag: 0.95,
    verticalThrust: 70, cruiseThrust: 14, cruiseAgl: 620, maxAgl: 820,
    enemyAwareMul: 0.55,
    exhaustProfile: {
      rate: 14, speed: 78, tint: 0xa8c4d8, smoke: 0x5a6570, sx: 0.72, sy: 0.22, life: 980, flame: 0.32, gap: 12, flameHue: 172,
    },
    sockets: [
      { id: "wing_hardpoint_1", class: "hardpoint", controller: "pilot", weapon: "hellfire_missile" },
      { id: "wing_hardpoint_2", class: "hardpoint", controller: "pilot", weapon: "hellfire_missile" },
      { id: "wing_hardpoint_3", class: "hardpoint", controller: "pilot", weapon: "gps_missile" },
      { id: "sensor_bay", class: "hardpoint", controller: "pilot", weapon: "tv_missile" },
    ],
    sensorPalette: "white_hot",
  },
  prometheus: {
    name: "Prometheus",
    fullName: "XV-99 Prometheus",
    role: "Alien Superweapon",
    description: "An enigmatic apparation of death, the Prometheus defies earthly physics to atomize enemy battle lines with volatile, high-energy alien weaponry.",
    flightModel: "vtol",
    sizeM: 14.7,
    ammoScale: 1.2,
    health: 130,
    radius: 36,
    height: 14,
    body: "craft_prometheus",
    hulk: "craft_prometheus_hulk",
    // No rotor — hover via energy FX later.
    rotOff: Math.PI / 2,
    forwardThrust: 900, strafeThrust: 760, maxSpeed: 600, minSpeed: 0, yawRate: 4.5, yawAccel: 25, drag: 0.95,
    verticalThrust: 700, cruiseThrust: 65, cruiseAgl: 90, maxAgl: 240,
    liftClass: "heavy",
    exhaustProfile: {
      rate: 26, speed: 72, tint: 0xc86cff, smoke: 0x6b3a78, sx: 0.98, sy: 0.28, life: 1320, flame: 0.58, gap: 10,
      flameHue: 248, glowFollowsHull: true,
    },
    sockets: [
      // Helix + Refractor share the belly gun UV (same pattern as Cyberhawk chin).
      { id: "belly_turret", class: "turret", controller: "pilot", weapon: "plasma_cannon", traverse: 260 },
      { id: "belly_beam", class: "turret", controller: "pilot", weapon: "laser_rocket", traverse: 260 },
      { id: "body_hardpoint", class: "hardpoint", controller: "pilot", weapon: "photon_missile" },
      { id: "bomb_bay", class: "hardpoint", controller: "pilot", weapon: "warp_bomb" },
    ],
    countermeasure: "phase_cloak",
    sensorPalette: "full_spectrum",
  },
  // Leviathan wingman — remote-only hull (not hangar-selectable).
  skiff: {
    name: "Skiff",
    fullName: "SKIFF Wingman",
    role: "Wingman Fighter",
    description: "The swarm of the Leviathan, the Skiff is a small, fast, and agile wingman that can be deployed to assist in combat.",
    playable: false,
    flightModel: "plane",
    controlScheme: "plane",
    sizeM: 6.4,
    ammoScale: 0.55,
    health: 36,
    radius: 14,
    height: 5,
    body: "craft_skiff",
    hulk: "craft_skiff_hulk",
    rotor: "craft_osprey_rotor",
    rotorHulk: "craft_osprey_rotor_hulk",
    rotorScale: 0.14,
    rotorInertia: 0.2,
    rotOff: Math.PI / 2,
    // Faster boom-and-zoom than the hangar biplane.
    forwardThrust: 520, reverseThrust: 360, strafeThrust: 0, maxSpeed: 380, minSpeed: 110, yawRate: 3.2, yawAccel: 13.5, drag: 1.3,
    verticalThrust: 120, cruiseThrust: 22, cruiseAgl: 160, maxAgl: 320,
    // White linger cloud off the aft exhaust UV. No nozzle flame.
    exhaustProfile: {
      rate: 16, speed: 24, tint: 0xffffff, smoke: 0xffffff, sx: 0.32, sy: 0.27, life: 1100, flame: 0, gap: 4,
    },
    sockets: [
      { id: "nose_guns", class: "fixed", controller: "pilot", weapon: "machine_gun", muzzleFire: "simultaneous" },
    ],
    countermeasure: "smoke_screen",
    enemySeekerMul: 0.72,
  },
  // Steampunk fighter pod — same plane scheme as biplane; launched from Leviathan.
  // Not hangar-selectable — remote roster owns lifecycle (`remoteSpecOf("fighter")`).
  raptor: {
    name: "Raptor",
    fullName: "Raptor Fighter",
    role: "Sky Leader",
    description: "A clockwork sky-commander, the Raptor functions as a sentient automaton that seamlessly hands control over to a human pilot to coordinate squad tactics and tear through enemy formations.",
    playable: false,
    flightModel: "plane",
    controlScheme: "plane",
    sizeM: 8.4,
    ammoScale: 0.7,
    health: 48,
    radius: 14,
    height: 6,
    body: "craft_raptor",
    hulk: "craft_raptor_hulk",
    rotor: "craft_osprey_rotor",
    rotorHulk: "craft_osprey_rotor_hulk",
    rotorScale: 0.18,
    rotorInertia: 0.22,
    rotOff: Math.PI / 2,
    forwardThrust: 520, reverseThrust: 320, strafeThrust: 0, maxSpeed: 400, minSpeed: 150, yawRate: 3.4, yawAccel: 14, drag: 1.2,
    // Match Leviathan operating band so the pod doesn't dive to biplane cruise.
    verticalThrust: 140, cruiseThrust: 24, cruiseAgl: 200, maxAgl: 380,
    // Light aft flame — steampunk single nozzle (UV on craft_raptor).
    exhaustProfile: {
      rate: 16,
      speed: 64,
      tint: 0xd4a878,
      smoke: 0x5a5550,
      sx: 0.52,
      sy: 0.18,
      life: 700,
      flame: 0.3,
      gap: 7,
      flameHue: 0,
    },
    sockets: [
      {
        id: "nose_guns",
        class: "fixed",
        controller: "pilot",
        weapon: "machine_gun",
        muzzleFire: "simultaneous",
      },
      {
        id: "wing_rockets",
        class: "hardpoint",
        controller: "pilot",
        weapon: "banshee",
        points: [{ id: "wing_l" }, { id: "wing_r" }],
      },
      {
        id: "bomb_bay",
        class: "hardpoint",
        controller: "pilot",
        weapon: "bomb",
        points: [{ id: "bay" }],
        bombDrop: { momentum: 0.4, maxBoost: 70, loft: 90, loftMax: 160 },
      },
    ],
    countermeasure: "smoke_screen",
    enemySeekerMul: 0.68,
    // Small POV pod — baseline harder to spot/chase than the host airship.
    enemyAwareMul: 0.62,
  },
  hover_tank: {
    name: "Wraith",
    fullName: "MHT-7 Wraith",
    role: "Heavy Ground Assault",
    description: "A powerful, low-altitude predator, the Wraith glides over any terrain to blast armor with hyper-velocity rail guns and advanced ordnance systems.",
    flightModel: "vtol",
    controlScheme: "orbit",
    crushesInfantry: true,
    sizeM: 9.5,
    ammoScale: 1.25,
    health: 220,
    radius: 28,
    height: 10,
    body: "craft_hover_tank",
    hulk: "craft_hover_tank_hulk",
    gunOverlayScale: 1.15,
    // Ground-hugger reads small on screen — pull the chase cam back.
    cameraScale: 0.72,
    flatHull: true,
    rotOff: Math.PI / 2,
    // Orbit yaw (A/D) + heli thrust (W/S). Mild reverse penalty — forward assault hull, not full
    // omnidirectional parity, but nowhere near as crippled as before.
    forwardThrust: 640, reverseThrust: 400, strafeThrust: 0, maxSpeed: 260, maxReverseSpeed: 190, minSpeed: 0, yawRate: 2.4, yawAccel: 12, drag: 1.8,
    verticalThrust: 380, cruiseThrust: 48, cruiseAgl: 18, maxAgl: 48,
    exhaustProfile: {
      rate: 22, speed: 88, tint: 0x70d8ff, smoke: 0x485761, sx: 0.95, sy: 0.28, life: 1100, flame: 0.48, gap: 10, flameHue: 172,
      // Rear vents are painted on the hull — keep the glow oval on body axes.
      glowFollowsHull: true,
    },
    sockets: [
      {
        id: "main_turret",
        class: "turret",
        controller: "pilot",
        weapon: "railgun",
        points: [{ id: "main" }],
        muzzleFire: "simultaneous",
        // Dual rails, slow volleys — cadence clearly below Cyber Hawk's chin rail.
        // 2 × (catalog / 0.48) ≈ similar DPS, much heavier pulse.
        fireRateMul: 0.48,
        gunTex: "craft_hover_tank_turret",
        gunHulk: "craft_hover_tank_turret_hulk",
        hullPlacement: "above",
        // Cupola rail — print larger than the coax MG on the same mount (bake 84px → ~1:1 draw).
        gunScale: 0.868,
        // Kick opposite turret aim (not hull heading).
        recoil: true,
      },
      {
        id: "coax_mg",
        class: "turret",
        controller: "automatic",
        weapon: "heavy_machine_gun",
        points: [{ id: "coax" }],
        // Draw above the rail turret on the shared cupola.
        hullPlacement: "above",
        gunScale: 0.72,
        crew: "coax",
      },
      {
        id: "spider_ports",
        class: "fixed",
        controller: "pilot",
        weapon: "spider_drone",
        muzzleFire: "alternate",
      },
      {
        id: "banshee_rack",
        class: "hardpoint",
        controller: "pilot",
        weapon: "banshee",
        hullPlacement: "above",
        points: [{ id: "wing_l" }, { id: "wing_r" }],
      },
    ],
    // Whip on the rail cupola — wobbles with hull + turret yaw.
    antenna: { length: 12, aft: 1.6, stiffness: 28, damping: 2.8, yawWhip: 12, lag: 1.8 },
    countermeasure: "reactive_armor",
    sensorPalette: "full_spectrum",
  },
  // Dropship AGV pod — dirt-locked tank drive; same Craft path as other remotes.
  // Not hangar-selectable — remote roster owns lifecycle (`remoteSpecOf("agv")`).
  hound: {
    name: "Hound",
    fullName: "HOUND AGV",
    role: "Ground Escort",
    description: "A versatile remote or autonomous pocket tank, the Hound tears through frontlines while designating targets to direct heavy remote artillery fire.",
    playable: false,
    // Heading-locked tank drive (A/D yaw, W/S along nose — no slide).
    flightModel: "ground",
    controlScheme: "orbit",
    crushesInfantry: true,
    sizeM: 4.2,
    ammoScale: 0.85,
    health: 140,
    radius: 14,
    // Tall enough that roof-turret leave clears dirt ripples (was 8 → skim kills).
    height: 14,
    body: "craft_hound",
    hulk: "craft_hound",
    gunOverlayScale: 0.88,
    cameraScale: 0.78,
    flatHull: true,
    track: "tread",
    trackGap: 8,
    trackScale: 0.82,
    rotOff: Math.PI / 2,
    // Orbit yaw + forward thrust; dirt-hugger (pad AGL enforced by remote snap).
    forwardThrust: 300, reverseThrust: 220, strafeThrust: 0, maxSpeed: 130, maxReverseSpeed: 70, minSpeed: 0, yawRate: 2.4, yawAccel: 12, drag: 1.85,
    verticalThrust: 200, cruiseThrust: 40, cruiseAgl: 3.5, maxAgl: 14,
    // Dark dust cloud off the rear grille. No nozzle flame.
    exhaustProfile: {
      rate: 7, speed: 16, tint: 0x5c5c58, smoke: 0x5c5c58, sx: 0.36, sy: 0.32, life: 3200, flame: 0, gap: 6,
    },
    sockets: [
      {
        id: "turret",
        class: "turret",
        controller: "pilot",
        weapon: "minigun",
        points: [{ id: "main" }],
        traverse: 360,
        gunTex: "gun_minigun",
        gunHulk: "gun_minigun_hulk",
        gunScale: 0.78,
        hullPlacement: "above",
      },
      {
        id: "missile_rack",
        class: "hardpoint",
        controller: "pilot",
        weapon: "photon_missile",
        hullPlacement: "above",
        ammo: 4,
      },
      {
        id: "howitzer_spot",
        class: "turret",
        controller: "pilot",
        weapon: "remote_howitzer",
      },
      {
        id: "strike_observer",
        class: "turret",
        controller: "pilot",
        weapon: "artillery_strike",
      },
    ],
    countermeasure: "smoke_screen",
    // Dirt runner — harder to spot than the dropship; seekers already ignore ground focus.
    enemyAwareMul: 0.7,
    enemySeekerMul: 0.78,
  },
  humvee: {
    name: "Humvee",
    fullName: "HUMVEE",
    role: "Ground Recon/Fire Support",
    description: "A manned fire-support escort deployed in pairs from the Chinook, holding tight to the flank and engaging hostiles at danger-close range.",
    playable: false,
    flightModel: "ground",
    controlScheme: "orbit",
    crushesInfantry: true,
    sizeM: 3.6,
    ammoScale: 0.9,
    health: 90,
    radius: 16,
    height: 12,
    body: "craft_humvee",
    hulk: "craft_humvee_hulk",
    gunOverlayScale: 0.85,
    cameraScale: 0.75,
    flatHull: true,
    track: "tire",
    trackGap: 10,
    trackScale: 0.8,
    wheels: 2,
    wheelDebrisScale: [0.62, 0.76],
    rotOff: Math.PI / 2,
    vehicleSteering: true,
    steerSpeedRef: 60,
    // Nimble wheeled scout — faster than the Hound, softer and single-armed.
    forwardThrust: 280, reverseThrust: 180, strafeThrust: 0, maxSpeed: 150, maxReverseSpeed: 70, minSpeed: 0, yawRate: 2.0, yawAccel: 10, drag: 1.8,
    verticalThrust: 180, cruiseThrust: 40, cruiseAgl: 3, maxAgl: 12,
    exhaustProfile: {
      rate: 5, speed: 14, tint: 0x5c5c58, smoke: 0x5c5c58, sx: 0.3, sy: 0.28, life: 2800, flame: 0, gap: 5,
    },
    sockets: [
      {
        id: "rws",
        class: "turret",
        controller: "pilot",
        weapon: "machine_gun",
        points: [{ id: "main" }],
        traverse: 360,
        gunTex: "craft_humvee_turret",
        gunHulk: "craft_humvee_turret_hulk",
        gunScale: 1.0,
        hullPlacement: "above",
      },
    ],
    // Small, quiet profile — harder to spot and lock than the Hound.
    enemyAwareMul: 0.75,
    enemySeekerMul: 0.8,
  },
  wolf: {
    name: "Wolf",
    fullName: "HDT HUNTER WOLF",
    role: "Ground Escort",
    description: "A heavily-armored tracked UGV, manned or autonomous, built around a lean chaingun-and-missile fit for direct firepower.",
    playable: false,
    flightModel: "ground",
    controlScheme: "orbit",
    crushesInfantry: true,
    sizeM: 4.0,
    ammoScale: 0.85,
    health: 130,
    radius: 14,
    height: 14,
    body: "craft_wolf",
    hulk: "craft_wolf_hulk",
    gunOverlayScale: 0.88,
    cameraScale: 0.78,
    flatHull: true,
    track: "tread",
    trackGap: 8,
    trackScale: 0.82,
    rotOff: Math.PI / 2,
    // Tracked and armored like the Hound — same drive feel, no artillery-spotter payload.
    forwardThrust: 300, reverseThrust: 220, strafeThrust: 0, maxSpeed: 128, maxReverseSpeed: 70, minSpeed: 0, yawRate: 2.3, yawAccel: 11, drag: 1.85,
    verticalThrust: 200, cruiseThrust: 40, cruiseAgl: 3.5, maxAgl: 14,
    exhaustProfile: {
      rate: 7, speed: 16, tint: 0x3c3c38, smoke: 0x3c3c38, sx: 0.36, sy: 0.32, life: 3200, flame: 0, gap: 6,
    },
    sockets: [
      {
        id: "turret",
        class: "turret",
        controller: "pilot",
        weapon: "minigun",
        points: [{ id: "main" }],
        traverse: 360,
        gunTex: "craft_wolf_turret",
        gunHulk: "craft_wolf_turret_hulk",
        gunScale: 0.95,
        hullPlacement: "above",
      },
      {
        id: "hardpoint",
        class: "hardpoint",
        controller: "pilot",
        weapon: "mini_hellfire_missile",
        hullPlacement: "above",
        ammo: 6,
      },
    ],
    // No countermeasure — realistic, no-frills loadout vs. the Hound's smoke screen.
    enemyAwareMul: 0.72,
    enemySeekerMul: 0.8,
  },
  vtol_dropship: {
    name: "Marauder",
    fullName: "UD-92 Marauder",
    role: "Heavy Air/Drop Assault",
    description: "A brutal assault dropship, the Marauder crashes through hostile defenses armed to the teeth to deploy a lethal pocket tank directly into the fray.",
    flightModel: "vtol",
    sizeM: 20.5,
    ammoScale: 1.5,
    health: 400,
    radius: 40,
    height: 16,
    body: "craft_vtol_dropship_v2",
    hulk: "craft_vtol_dropship_v2_hulk",
    rotor: "craft_osprey_rotor",
    rotorHulk: "craft_osprey_rotor_hulk",
    rotorScale: 0.66,
    rotorInertia: 1.35,
    // Heavy hauler stays upright — no strafe bank lean.
    flatHull: true,
    rotOff: Math.PI / 2,
    // Tough hauler: Chinook-class armor feel, sluggish turn / strafe — lumbering escort pace.
    // Reverse is weak — big VTOL backs up carefully.
    forwardThrust: 360, reverseThrust: 180, strafeThrust: 160, maxSpeed: 160, maxReverseSpeed: 70, minSpeed: 0, yawRate: 1.0, yawAccel: 4.2, drag: 1.9,
    verticalThrust: 380, cruiseThrust: 36, cruiseAgl: 70, maxAgl: 180,
    liftClass: "heavy",
    exhaustProfile: {
      rate: 20, speed: 92, tint: 0xa8c4d8, smoke: 0x5a6570, sx: 0.88, sy: 0.26, life: 1050, flame: 0.42, gap: 11, flameHue: 172,
    },
    sockets: [
      {
        id: "chin_gun",
        class: "turret",
        controller: "automatic",
        weapon: "chain_gun",
        points: [{ id: "chin" }],
        traverse: 240,
        muzzleFire: "simultaneous",
        gunTex: "gun_dual_chain",
        gunScale: 0.5,
        crew: "belly",
      },
      {
        id: "miniguns",
        class: "turret",
        controller: "automatic",
        weapon: "minigun",
        // One HUD slot; AI aims each barrel independently. Full-circle traverse each, but
        // preferred headings split so they don't all crowd the same forward targets.
        points: [
          { id: "side_l", heading: -45, hullPlacement: "below" },
          { id: "side_r", heading: 45, hullPlacement: "below" },
          { id: "dorsal", heading: 0, hullPlacement: "above" },
        ],
        traverse: 360,
        muzzleFire: "simultaneous",
        gunScale: 0.5,
        crew: "door",
      },
      {
        id: "howitzer_turret",
        class: "turret",
        controller: "pilot",
        weapon: "heavy_artillery",
        points: [{ id: "howitzer" }],
        traverse: 200,
        hullPlacement: "above",
        recoil: true,
        crew: "dorsal",
      },
      {
        id: "starstreak_racks",
        class: "hardpoint",
        controller: "pilot",
        weapon: "swarm_missile",
        points: [
          { id: "wing_l0" },
          { id: "wing_r0" },
          { id: "wing_l1" },
          { id: "wing_r1" },
        ],
      },
      { id: "cargo_bay", class: "hardpoint", controller: "pilot", weapon: "agv_drop", points: [{ id: "ramp" }], heading: 180 },
    ],
    countermeasure: "flares",
  },
  airship: {
    name: "Leviathan",
    fullName: "Leviathan Airship",
    role: "Sky Fortress",
    description: "A colossal steampunk juggernaut, the Leviathan dominates the skies by unleashing massive rocket swarms, relentless streams of cannon fire, and a fleet of deployable aircraft.",
    // Gunship-style loiter: A/D yaw, W/S trim, mouse aims stores.
    flightModel: "plane",
    controlScheme: "orbit",
    sizeM: 68,
    ammoScale: 2.4,
    health: 480,
    radius: 118,
    height: 72,
    body: "craft_airship",
    hulk: "craft_airship_hulk",
    // Propellers are composited (nacelle + stern + bow mounts) — not painted into body art.
    rotor: "craft_osprey_rotor",
    rotorHulk: "craft_osprey_rotor_hulk",
    rotorScale: 0.34,
    rotorInertia: 0.55,
    // Sky fortress stays upright — no A/D bank lean.
    flatHull: true,
    rotOff: Math.PI / 2,
    forwardThrust: 280, strafeThrust: 0, maxSpeed: 160, minSpeed: 70, yawRate: 0.55, yawAccel: 1.4, drag: 1.85,
    verticalThrust: 70, cruiseThrust: 16, cruiseAgl: 220, maxAgl: 380,
    liftClass: "heavy",
    // Twin stern vents — warm steampunk wash (UVs on craft_airship).
    // flameHue 0 = source orange sheet (`fx_flame`); only 172/185/248 are pre-baked.
    exhaustProfile: {
      rate: 16,
      speed: 48,
      tint: 0xd4a878,
      smoke: 0x5a5048,
      sx: 1.35,
      sy: 0.48,
      life: 1680,
      flame: 0.38,
      gap: 16,
      flameHue: 0,
      glowFollowsHull: true,
    },
    sockets: [
      // Top-center revolving grenade lob — pilot turret, iron-bomb arc.
      {
        id: "grenade_turret",
        class: "turret",
        controller: "pilot",
        weapon: "grenade_launcher",
        points: [{ id: "grenade" }],
        traverse: 240,
        hullPlacement: "above",
        gunScale: 1.05,
        bombDrop: { momentum: 0.2, maxBoost: 180, loft: 150, loftMax: 270 },
      },
      // Four deck .50s — one HUD slot; each barrel aims/fires independently.
      {
        id: "deck_fifties",
        class: "turret",
        controller: "automatic",
        weapon: "heavy_machine_gun",
        points: [
          { id: "bow_l", heading: -20 },
          { id: "bow_r", heading: 20 },
          { id: "flank_l", heading: -90 },
          { id: "flank_r", heading: 90 },
        ],
        traverse: 220,
        hullPlacement: "above",
        gunScale: 0.85,
        crew: "door",
      },
      {
        id: "banshee_racks",
        class: "hardpoint",
        controller: "pilot",
        weapon: "banshee",
        hullPlacement: "above",
        points: [
          { id: "star_l0" },
          { id: "star_r0" },
          { id: "star_l1" },
          { id: "star_r1" },
          { id: "star_l2" },
          { id: "star_r2" },
          { id: "star_l3" },
          { id: "star_r3" },
          { id: "star_l4" },
          { id: "star_r4" },
        ],
      },
      {
        id: "skiff_bay",
        class: "hardpoint",
        controller: "pilot",
        weapon: "wingman_drone",
        hullPlacement: "above",
        heading: 180,
        points: [{ id: "skiff" }],
        // Cap the bay at 6 Skiffs regardless of the airship's ammoScale.
        ammo: 6,
      },
      {
        id: "fighter_bay",
        class: "hardpoint",
        controller: "pilot",
        weapon: "fighter_pod",
        hullPlacement: "above",
        heading: 180,
        points: [{ id: "skiff" }],
        // One Raptor, regardless of the airship's ammoScale.
        ammo: 1,
      },
    ],
    sensorPalette: "black_hot",
  },
  biplane: {
    name: "Red Baron",
    fullName: "Fokker Dr.I",
    role: "Dogfighter",
    description: "A fragile relic of a bygone era, test your skills with nimble dogfighting maneuvers and the power to call in devastating artillery strikes.",
    flightModel: "plane",
    controlScheme: "plane",
    sizeM: 7.2,
    ammoScale: 0.55,
    health: 55,
    radius: 16,
    height: 6,
    body: "craft_biplane",
    hulk: "craft_biplane_hulk",
    rotor: "craft_osprey_rotor",
    rotorHulk: "craft_osprey_rotor_hulk",
    rotorScale: 0.16,
    rotorInertia: 0.22,
    sensorPalette: "night_vision",
    rotOff: Math.PI / 2,
    // Slow but agile: little thrust differential; plane yaw a touch slower than the snap gun.
    forwardThrust: 420, reverseThrust: 380, strafeThrust: 0, maxSpeed: 280, minSpeed: 90, yawRate: 3.15, yawAccel: 13, drag: 1.45,
    verticalThrust: 110, cruiseThrust: 20, cruiseAgl: 90, maxAgl: 220,
    sockets: [
      { id: "nose_guns", class: "fixed", controller: "pilot", weapon: "machine_gun", muzzleFire: "simultaneous" },
      {
        id: "observer",
        class: "turret",
        controller: "pilot",
        weapon: "artillery_strike",
        points: [{ id: "cockpit" }],
        hullPlacement: "above",
        gunScale: 0.52,
      },
      {
        id: "wing_rockets",
        class: "hardpoint",
        controller: "pilot",
        weapon: "incendiary_rocket",
        points: [{ id: "wing_l" }, { id: "wing_r" }],
      },
      {
        id: "bomb_bay",
        class: "hardpoint",
        controller: "pilot",
        weapon: "bomb",
        points: [{ id: "bay" }],
        bombDrop: { momentum: 0.4, maxBoost: 70, loft: 90, loftMax: 160 },
      },
    ],
    countermeasure: "smoke_screen",
    enemySeekerMul: 0.72,
  },
};

/** Homogeneous catalog (keys stay literal via CraftKind). */
export const CRAFTS: Record<CraftKind, CraftSpec> = Object.fromEntries(
  Object.entries(CRAFTS_DEFS).map(([kind, def]) => [kind, { ...def, kind }])
) as Record<CraftKind, CraftSpec>;
