/** Mission catalog. */
import type { MissionKind, MissionSpec } from "../sim/mission";

export const MISSIONS: Record<MissionKind, MissionSpec> = {
  river_run: {
    kind: "river_run",
    label: "RIVER RUN",
    briefing: "River valley · mixed armor, air defenses, and river patrols",
    profile: {
      id: "river_run",
      landBias: 0,
      relief: 1,
      edgeFalloff: 0.12,
      shape: "valley",
      warp: 1,
      theme: "temperate",
      riverTarget: 50,
      mainRivers: 1,
      landforms: { mesa: 0, crater: 0, volcano: 0, dunes: 0 },
      objectiveCount: 4,
      siting: "tactical",
      garrisonScale: 1,
      patrolCount: 22,
      waterPatrolBias: 1,
      forceMix: "mixed",
      roadDensity: 1,
      clouds: 1,
    },
  },
  coastal_strike: {
    kind: "coastal_strike",
    label: "COASTAL STRIKE",
    briefing: "Open water · naval concentrations and exposed coastal objectives",
    profile: {
      id: "coastal_strike",
      landBias: -0.04,
      relief: 1.08,
      edgeFalloff: 0.05,
      shape: "coast",
      warp: 1,
      theme: "coastal",
      riverTarget: 12,
      mainRivers: 0,
      landforms: { mesa: 0, crater: 0, volcano: 0, dunes: 0 },
      objectiveCount: 3,
      siting: "tactical",
      garrisonScale: 0.78,
      patrolCount: 30,
      waterPatrolBias: 2.4,
      forceMix: "naval",
      roadDensity: 1,
      clouds: 1,
    },
  },
  island_chain: {
    kind: "island_chain",
    label: "ISLAND CHAIN",
    briefing: "Scattered islands across open sea · island-hop between fortified outposts under naval patrol",
    profile: {
      id: "island_chain",
      landBias: -0.05,
      relief: 1.3,
      edgeFalloff: 0,
      shape: "archipelago",
      warp: 1,
      theme: "tropic",
      riverTarget: 4,
      mainRivers: 0,
      landforms: { mesa: 0, crater: 0, volcano: 1, dunes: 0 },
      objectiveCount: 4,
      siting: "tactical",
      garrisonScale: 0.6,
      patrolCount: 26,
      waterPatrolBias: 2.6,
      forceMix: "naval",
      roadDensity: 1,
      clouds: 1,
    },
  },
  highland_siege: {
    kind: "highland_siege",
    label: "HIGHLAND SIEGE",
    briefing: "Frozen high plateau · dense fortified positions and heavy armor",
    profile: {
      id: "highland_siege",
      landBias: 0.03,
      relief: 1.15,
      edgeFalloff: 0.1,
      shape: "plateau",
      warp: 0.8,
      theme: "arctic",
      riverTarget: 18,
      mainRivers: 0,
      landforms: { mesa: 0, crater: 2, volcano: 0, dunes: 0 },
      objectiveCount: 5,
      siting: "tactical",
      garrisonScale: 1.3,
      patrolCount: 28,
      waterPatrolBias: 0.35,
      forceMix: "heavy",
      roadDensity: 1,
      clouds: 1,
    },
  },
  desert_flats: {
    kind: "desert_flats",
    label: "DESERT FLATS",
    briefing: "Open desert flats · long sightlines, armored columns and scattered scrub",
    profile: {
      id: "desert_flats",
      landBias: -0.13,
      relief: 0.2,
      edgeFalloff: 0,
      shape: "open",
      warp: 0.6,
      theme: "desert",
      riverTarget: 0,
      mainRivers: 0,
      landforms: { mesa: 5, crater: 1, volcano: 0, dunes: 3 },
      objectiveCount: 4,
      siting: "tactical",
      garrisonScale: 1,
      patrolCount: 24,
      waterPatrolBias: 0.35,
      forceMix: "heavy",
      roadDensity: 1,
      clouds: 0.3,
    },
  },
  custom: {
    kind: "custom",
    label: "CUSTOM",
    briefing: "User-defined terrain, objectives, and force composition",
    profile: {
      id: "custom",
      landBias: 0,
      relief: 1,
      edgeFalloff: 0.18,
      shape: "open",
      warp: 0.5,
      theme: "temperate",
      riverTarget: 40,
      mainRivers: 0,
      landforms: { mesa: 0, crater: 0, volcano: 0, dunes: 0 },
      objectiveCount: 4,
      siting: "tactical",
      garrisonScale: 1,
      patrolCount: 22,
      waterPatrolBias: 1,
      forceMix: "mixed",
      roadDensity: 1,
      clouds: 1,
    },
  },
};
