/** Mission catalog. */
import type { MissionKind, MissionSpec } from "../sim/mission";

export const MISSIONS: Record<MissionKind, MissionSpec> = {
  river_run: {
    kind: "river_run",
    label: "RIVER RUN",
    briefing: "Balanced terrain · mixed armor, air defenses, and river patrols",
    profile: {
      id: "river_run",
      landBias: 0,
      relief: 1,
      edgeFalloff: 0.18,
      riverTarget: 50,
      objectiveCount: 4,
      garrisonScale: 1,
      patrolCount: 22,
      waterPatrolBias: 1,
      forceMix: "mixed",
      roadDensity: 1,
      clouds: 1,
    },
  },
  coastal_strike: {
    kind: "coastal_strike",
    label: "COASTAL STRIKE",
    briefing: "Open water · naval concentrations and exposed coastal objectives",
    profile: {
      id: "coastal_strike",
      landBias: -0.1,
      relief: 1.08,
      edgeFalloff: 0.42,
      riverTarget: 12,
      objectiveCount: 3,
      garrisonScale: 0.78,
      patrolCount: 30,
      waterPatrolBias: 2.4,
      forceMix: "naval",
      roadDensity: 1,
      clouds: 1,
    },
  },
  island_chain: {
    kind: "island_chain",
    label: "ISLAND CHAIN",
    briefing: "Scattered islands across open sea · island-hop between fortified outposts under naval patrol",
    profile: {
      id: "island_chain",
      landBias: -0.34,
      relief: 1.4,
      edgeFalloff: 0.1,
      riverTarget: 4,
      objectiveCount: 4,
      garrisonScale: 0.6,
      patrolCount: 26,
      waterPatrolBias: 2.6,
      forceMix: "naval",
      roadDensity: 1,
      clouds: 1,
    },
  },
  highland_siege: {
    kind: "highland_siege",
    label: "HIGHLAND SIEGE",
    briefing: "Broken high ground · dense fortified positions and heavy armor",
    profile: {
      id: "highland_siege",
      landBias: 0.08,
      relief: 1.32,
      edgeFalloff: 0.1,
      riverTarget: 18,
      objectiveCount: 5,
      garrisonScale: 1.3,
      patrolCount: 28,
      waterPatrolBias: 0.35,
      forceMix: "heavy",
      roadDensity: 1,
      clouds: 1,
    },
  },
  desert_flats: {
    kind: "desert_flats",
    label: "DESERT FLATS",
    briefing: "Open desert flats · long sightlines, armored columns and scattered scrub",
    profile: {
      id: "desert_flats",
      landBias: -0.135,
      relief: 0.2,
      edgeFalloff: 0,
      riverTarget: 0,
      objectiveCount: 4,
      garrisonScale: 1,
      patrolCount: 24,
      waterPatrolBias: 0.35,
      forceMix: "heavy",
      roadDensity: 1,
      clouds: 0.3,
    },
  },
  custom: {
    kind: "custom",
    label: "CUSTOM",
    briefing: "User-defined terrain, objectives, and force composition",
    profile: {
      id: "custom",
      landBias: 0,
      relief: 1,
      edgeFalloff: 0.18,
      riverTarget: 40,
      objectiveCount: 4,
      garrisonScale: 1,
      patrolCount: 22,
      waterPatrolBias: 1,
      forceMix: "mixed",
      roadDensity: 1,
      clouds: 1,
    },
  },
};
